## ----------- Camera 1 ----------- ##

- ros_topic_name: "cam1/camera_info"
  gz_topic_name: "cam1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: ROS_TO_GZ

- ros_topic_name: "cam1/image_raw"
  gz_topic_name: "cam1/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

## ----------- Camera 2 ----------- ##

- ros_topic_name: "cam2/camera_info"
  gz_topic_name: "cam2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: ROS_TO_GZ

- ros_topic_name: "cam2/image_raw"
  gz_topic_name: "cam2/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

## ----------- Camera 3 ----------- ##

- ros_topic_name: "cam3/camera_info"
  gz_topic_name: "cam3/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: ROS_TO_GZ

- ros_topic_name: "cam3/image_raw"
  gz_topic_name: "cam3/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

## ----------- Camera 4 ----------- ##

- ros_topic_name: "cam4/camera_info"
  gz_topic_name: "cam4/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: ROS_TO_GZ

- ros_topic_name: "cam4/image_raw"
  gz_topic_name: "cam4/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS