controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_wheel_drive_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

omni_wheel_drive_controller:
  ros__parameters:
    use_sim_time: true
    wheel_offset: 0.785398
    wheel_names:
      - "chassis_to_wheel_c"
      - "chassis_to_wheel_a"
      - "chassis_to_wheel_d"
      - "chassis_to_wheel_b"
    robot_radius: 0.188 
    wheel_radius: 0.034925 
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    open_loop: true
    position_feedback: false
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    publish_limited_velocity: true